### ISSUE TITLE
Problems on running va_benchmark.py

### ISSUE THREAD

**Issue by shaw0908** [SpiNNakerManchester/PyNNExamples#12]
Deal all, 
     I am configuring my computer strictly after http://spinnakermanchester.github.io/spynnaker/4.0.0/PyNNOnSpinnakerInstall.html#LocalBoard . When I try to run the example va_benchmark.py , I was told 

**2018-05-26 14:12:45 WARNING: Application will not actually be run as on a virtual board
2018-05-26 14:12:45 INFO: Time 0:00:00.000490 taken by DatabaseInterface
2018-05-26 14:12:45 WARNING: The simulation is using a virtual machine and so has not truly ran, hence the list will be empty**

Here is my .spinnaker.cfg:
**virtual_board = True
width = 8
height = 8**

And the graph given after  the simulation has only two axis,x and y. There is not spikes on the graph as expected. I am super new to this area. I am using linux Ubuntu 16.04. And download the spiNNaker etc under user mode. 

Any help would be appreciated, Thanks

**Comment by alan-stokes** [comment]
a virtual board is used to debug/test that your pynn script will run through the mapping process of the SpiNNaker software. It is NOT a emulation of a SpiNNaker machine. Therefore its not possible to run your script, as you have not yet told the tools what SpiNNaker machine your using. 

change the cfg file to use
spinnaker_machine = ip_address
version = 5/4/3/2

or 
spalloc_server = ip_address
spalloc_user = your name

or 
utilise the HBP portal from here:
https://services.humanbrainproject.eu/oidc/login

hope this helps
