### ISSUE TITLE
Parameter choice in structural + STDP example

### ISSUE THREAD

**Issue by andrewgait** [SpiNNakerManchester/PyNNExamples#31]
https://github.com/SpiNNakerManchester/PyNN8Examples/blob/1d36636a195bb5439fff6ea44b1eb42c0d764508/examples/structural_plasticity_with_stdp_2d.py#L188

I find the above parameter choice in conjunction with the elimination_weight threshold value somewhat strange; it seems to me from running this a few times as though the desired effect on the post-population does not take place, possibly because any newly-created synapses are then subsequently eliminated?  Choosing parameters similar to those in the non-STDP example (i.e. elimination_weight threshold = initial_weight = 0.2) gives the effect on the post-population that I would expect to see...

**Comment by pabogdan** [comment]
I would like to make it obvious that STDP still works in the same way as in `stdp_example.py`. For this, I would like weights to start at 0 to show that STDP does indeed function. To make it obvious that weight increases are happening we can increase the A_plus of the STDP + eliminate all p_elim + increase s_max (just to be sure that sufficient connections are formed). 

I've also just realised that there's a typo in `potentiatiated` that should be addressed at some point.
```
elimination_weight = sim.RandomByWeightElimination(
    prob_elim_potentiatiated=0,
    prob_elim_depressed=0,
    threshold=0.5  # Use same weight as initial weight for static connections
)
structure_model_with_stdp = sim.StructuralMechanismSTDP(
    # Partner selection, formation and elimination rules from above
    partner_selection_last_neuron, formation_distance, elimination_weight,
    # Use this weight when creating a new synapse
    initial_weight=0,
    # Use this weight for synapses at start of simulation
    weight=0,
    # Use this delay when creating a new synapse
    initial_delay=10,
    # Use this weight for synapses at the start of simulation
    delay=10,
    # Maximum allowed fan-in per target-layer neuron
    s_max=64,
    # Frequency of rewiring in Hz
    f_rew=10 ** 4,
    # STDP rules
    timing_dependence=sim.SpikePairRule(
        tau_plus=20., tau_minus=20.0, A_plus=0.1, A_minus=0.02),
    weight_dependence=sim.AdditiveWeightDependence(w_min=0, w_max=1.)
)
```

**Comment by andrewgait** [comment]
This has been dealt with, so closing.
