### ISSUE TITLE
can we use FromListConnector() for multiple layers?

### ISSUE THREAD

**Issue by aitsam12** [SpiNNakerManchester/PyNNExamples#83]
Hi,
I am kinda new in this field. Luckily I have SpiNNaker 5 board to do the experiments.
I used snntoolbox to convert ANN to SNN with NEURON simulator for MNIST dataset. By doing that, I got text files for each layer which contain these four columns (i, j, weight, delay). 

I am using FromListConnector() in PyNN to use the txt file, something like this:

stdp_proj = p.Projection(presynaptic_population = inp,
             postsynaptic_population = exc,
             connector = p.FromListConnector(**txt file loaded by using numpy**),
             synapse_type = stdp_model,
             receptor_type = 'excitatory'
            )

I tried with 7Dense_10 layer for now and it worked but results are not really good (I don't know why). **Question:** is it possible to use multiple layers with FromListConnector()? If yes, then how? If No, then what are the ways to use this class efficiently?

**Question 2:** How to measure accuracy after running the SNN model on SpiNNaker? and how to measure power consumption and total time?

Thank you in advance.

**Comment by Christian-B** [comment]
general use questions are better emailed to spinnakerusers@googlegroups.com than posted as issues.

Each connector including FromListConnectors  connect exactly one Population to One other (or same) Population.

There can be as many From List connectors as you like (Assuming the whole network fits on your board)

Do note the FromListConnector is the the most expensive connector in terms of time to load onto the machine

"accuracy" is relative to the model so there are no automated tools to measure that.

You can turn on energy reports using the cfg setting:
[Reports] write_energy_report = True
There is however ongoing work to in regards to the Energy Reports as they have fallen behind especially if you are running more than once or for a long time.
